// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZstIWSQ-ILJHekMzVkN1Eevdsb9HTj4I',
    appId: '1:517308029732:web:3e7bc17ece147428bcb1b1',
    messagingSenderId: '517308029732',
    projectId: 'flutter-rent-car-87db3',
    authDomain: 'flutter-rent-car-87db3.firebaseapp.com',
    storageBucket: 'flutter-rent-car-87db3.firebasestorage.app',
    measurementId: 'G-NJEE5K70XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr-CdgeigaupDXM_9ZQCfhCvadJPtlsOQ',
    appId: '1:517308029732:android:934e4c7b247a8e28bcb1b1',
    messagingSenderId: '517308029732',
    projectId: 'flutter-rent-car-87db3',
    storageBucket: 'flutter-rent-car-87db3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClMRClgvejhkMlPe0Sbd-2S2RUY6hH-io',
    appId: '1:517308029732:ios:16a0d8a077c9878cbcb1b1',
    messagingSenderId: '517308029732',
    projectId: 'flutter-rent-car-87db3',
    storageBucket: 'flutter-rent-car-87db3.firebasestorage.app',
    iosBundleId: 'com.example.flutterCarRentalAppCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClMRClgvejhkMlPe0Sbd-2S2RUY6hH-io',
    appId: '1:517308029732:ios:16a0d8a077c9878cbcb1b1',
    messagingSenderId: '517308029732',
    projectId: 'flutter-rent-car-87db3',
    storageBucket: 'flutter-rent-car-87db3.firebasestorage.app',
    iosBundleId: 'com.example.flutterCarRentalAppCleanArchitecture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZstIWSQ-ILJHekMzVkN1Eevdsb9HTj4I',
    appId: '1:517308029732:web:b217ed90461e85ecbcb1b1',
    messagingSenderId: '517308029732',
    projectId: 'flutter-rent-car-87db3',
    authDomain: 'flutter-rent-car-87db3.firebaseapp.com',
    storageBucket: 'flutter-rent-car-87db3.firebasestorage.app',
    measurementId: 'G-WKNZHBJDBH',
  );
}
